/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#79FF8D',
        secondary: '#FFED85',
        'secondary-hover': '#A7FFB4',
        'custom-black': '#1A1A1A',
        'custom-green-light': '#92DE9E',
        'custom-green': '#5BBF6A',
        'custom-green-dark': '#2A5931',
        'custom-yellow-light': '#FFFBE3',
        'custom-cream-light': '#FAFFF4',
        'custom-coral-dark': '#FB8888',
        'custom-blue-light': '#C5ECFF',
        'custom-gray-dark': '#333333',
        'custom-gray-medium': '#656565',
        'custom-gray': '#8D8D8D',
        'custom-gray-light': '#E7E7E7',
        'custom-gray-lighter': '#F7F7F7',
        'custom-gray-800': '#424242',
        'custom-gray-700': '#616161',
        'custom-gray-600': '#757575',
        'custom-gray-500': '#9e9e9e',
        'custom-gray-400': '#bdbdbd',
        'custom-gray-300': '#e0e0e0',
        'custom-gray-200': '#eeeeee',
        'custom-gray-100': '#f5f5f5',
        'custom-gray-h': '#4D4D4D',
        'custom-gray-light-h': '#CBCBCB',
        'custom-kakao-yellow': '#FEE500',
        'custom-green-money': '#79FF8D',
        'hover-30': '#CBCBCB',
        'hover-80': '#4D4D4D',
        'green-hover': '#A7FFB4',
        modal: '#3E3E3E',
        'custom-black-light': '#202020',
        edit: '#D3D3D3',
        view: '#FBFBFB',
        'view-bg': '#C2C2C2',
        'quiz-bg': '#F3F4F6',
        'quiz-correct-bg': '#CDFFE8',
        'quiz-wrong-bg': '#FFE7E7',
        'gray-070': '#616161',
        'new-green': '#06EA82',
        'active-green': '#1bba71',
        inactive: '#d9d9d9',
        'calendar-gray': '#999999',
      },
      screens: {
        desktop: { min: '1440px' },
      },
      boxShadow: {
        custom: '0px 4px 8px rgba(0, 0, 0, 0.3)',
        login: '0px 6px 12px rgba(0, 0, 0, 0.3)',
        top: '0 -4px 8px rgba(0, 0, 0, 0.2)',
        'wcal-both': '2px 2px 10px rgba(0,0,0,0.05), -2px -2px 10px rgba(0,0,0,0.05)',
      },
      backgroundImage: {
        unchecked: "url('@/assets/icons/icon_checkbox_false.svg')",
        checked: "url('@/assets/icons/icon_checkbox_true.svg')",
        play: "url('@/assets/icons/video_btn_style=main.svg')",
        'play-hover': "url('@/assets/icons/video_btn_style=hover.svg')",
        'play-disabled': "url('@/assets/icons/video_btn_style=disabled.svg')",
        keynote: "url('@/assets/P2_5d/icon_Keynote.svg')",
        scrap: "url('@/assets/P2_5d/icon_scrap.svg')",
        event: "url('@/assets/icons/star.svg')",
      },
      lineHeight: {
        170: '1.7',
        160: '1.6',
        120: '1.2',
      },
      animation: {
        'toast-slide-in': 'toastSlideIn 0.1s ease-out forwards',
        'toast-slide-out': 'toastSlideOut 0.1s ease-in forwards',
      },
      keyframes: {
        toastSlideIn: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        toastSlideOut: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(100%)' },
        },
      },
    },
  },
  plugins: [],
  darkMode: 'class',
};
